composers = ["Aird's Airs",
"Johann Sebastian Bach",
"Ludwig van Beethoven",
"Johannes Ciconia",
"Arcangelo Corelli",
"C.P.E. Bach",
"Demonstration Files",
"Essen Folksong Collection",
"George Frideric Handel",
"Joseph Haydn",
"Josquin des Prez",
"Leadsheet demos",
"D. Luca",
"Miscellaneous Folk",
"Claudio Monteverdi",
"Wolfgang Amadeus Mozart",
"Oneill's 1850 Collection",
"Giovanni Palestrina",
"Ryan's Mammoth Collection",
"Arnold Schoenberg",
"Robert Schumann",
"Clara Schumann",
"Theory Exercises",
"Fourteenth-Century Italian Music",
"Giuseppe Verdi",
"Carl Maria von Weber"]

print composers
